import { WeatherForecast } from 'src/app/models/forecast.model';
import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DummyDataService {

  constructor(){  }

  weatherData(){
    console.info("adding dummy data..");
    const inCelsius = true;

    const currentDateTime = new Date().toISOString(); // e.g., "2024-12-30T12:45:00.000Z"
    const lastUpdatedTime = new Date().toISOString(); // e.g., "2024-12-30T12:30:00.000Z"

    const iconURL = "https://www.example.com/weather-icon.png"; // Replace with an actual icon URL
    const cityName = "San Francisco";
    const weatherStatus = "Sunny";
    const humidity = 65; // in percentage
    const wind = 12; // in km/h

    const minTemp_c = 10; // in °C
    const maxTemp_c = 22; // in °C
    const temperature_c = 18; // in °C

    const minTemp_f = (minTemp_c * 9) / 5 + 32; // in °F
    const maxTemp_f = (maxTemp_c * 9) / 5 + 32; // in °F
    const temperature_f = (temperature_c * 9) / 5 + 32; // in °F
  }

  forecastData() {
    console.warn('Creating and Using dummy data.');
    // Create a WeatherForecast object
    const forecastData: WeatherForecast = {
      location: {
        name: "New York",
        region: "New York",
        country: "United States",
        lat: 40.7128,
        lon: -74.006,
        tz_id: "America/New_York",
        localtime_epoch: 1704067200,
        localtime: "2025-01-04 12:00"
      },
      current: {
        last_updated_epoch: 1704063600,
        last_updated: "2025-01-04 11:00",
        temp_c: 5.0,
        temp_f: 41.0,
        is_day: 1,
        condition: {
          text: "Partly Cloudy",
          icon: "//cdn.weatherapi.com/weather/64x64/day/116.png",
          code: 1003
        },
        wind_mph: 10.0,
        wind_kph: 16.1,
        wind_degree: 270,
        wind_dir: "W",
        pressure_mb: 1015,
        pressure_in: 29.97,
        precip_mm: 0.0,
        precip_in: 0.0,
        humidity: 65,
        cloud: 50,
        feelslike_c: 2.0,
        feelslike_f: 35.6,
        vis_km: 10.0,
        vis_miles: 6.2,
        uv: 3,
        gust_mph: 15.0,
        gust_kph: 24.1
      },
      forecast: {
        forecastday: [
          {
            date: "2025-01-04",
            date_epoch: 1704067200,
            day: {
              maxtemp_c: 7.0,
              maxtemp_f: 44.6,
              mintemp_c: -1.0,
              mintemp_f: 30.2,
              avgtemp_c: 3.0,
              avgtemp_f: 37.4,
              maxwind_mph: 12.0,
              maxwind_kph: 19.3,
              totalprecip_mm: 0.0,
              totalprecip_in: 0.0,
              totalsnow_cm: 0.0,
              avgvis_km: 10.0,
              avgvis_miles: 6.2,
              avghumidity: 70,
              daily_will_it_rain: 0,
              daily_chance_of_rain: 0,
              daily_will_it_snow: 0,
              daily_chance_of_snow: 0,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000
              },
              uv: 4
            },
            astro: {
              sunrise: "07:20 AM",
              sunset: "04:40 PM",
              moonrise: "06:15 PM",
              moonset: "07:05 AM",
              moon_phase: "Waning Gibbous",
              moon_illumination: 85,
              is_moon_up: 1,
              is_sun_up: 1
            },
            hour: [
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 10:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Sunny",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Partly Cloudy",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/116.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Patchy rain nearby",
                  icon: "//cdn.weatherapi.com/weather/64x64/day/176.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Patchy freezing drizzle nearby",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/185.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Thundery outbreaks in nearby",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/200.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              },
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              }
            ]
          },
          {
            date: "2025-01-05",
            date_epoch: 1704067200,
            day: {
              maxtemp_c: 7.0,
              maxtemp_f: 44.6,
              mintemp_c: -1.0,
              mintemp_f: 30.2,
              avgtemp_c: 3.0,
              avgtemp_f: 37.4,
              maxwind_mph: 12.0,
              maxwind_kph: 19.3,
              totalprecip_mm: 0.0,
              totalprecip_in: 0.0,
              totalsnow_cm: 0.0,
              avgvis_km: 10.0,
              avgvis_miles: 6.2,
              avghumidity: 70,
              daily_will_it_rain: 0,
              daily_chance_of_rain: 0,
              daily_will_it_snow: 0,
              daily_chance_of_snow: 0,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000
              },
              uv: 4
            },
            astro: {
              sunrise: "07:20 AM",
              sunset: "04:40 PM",
              moonrise: "06:15 PM",
              moonset: "07:05 AM",
              moon_phase: "Waning Gibbous",
              moon_illumination: 85,
              is_moon_up: 1,
              is_sun_up: 1
            },
            hour: [
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              }
            ]
          },
          {
            date: "2025-01-06",
            date_epoch: 1704067200,
            day: {
              maxtemp_c: 7.0,
              maxtemp_f: 44.6,
              mintemp_c: -1.0,
              mintemp_f: 30.2,
              avgtemp_c: 3.0,
              avgtemp_f: 37.4,
              maxwind_mph: 12.0,
              maxwind_kph: 19.3,
              totalprecip_mm: 0.0,
              totalprecip_in: 0.0,
              totalsnow_cm: 0.0,
              avgvis_km: 10.0,
              avgvis_miles: 6.2,
              avghumidity: 70,
              daily_will_it_rain: 0,
              daily_chance_of_rain: 0,
              daily_will_it_snow: 0,
              daily_chance_of_snow: 0,
              condition: {
                text: "Sunny",
                icon: "//cdn.weatherapi.com/weather/64x64/day/113.png",
                code: 1000
              },
              uv: 4
            },
            astro: {
              sunrise: "07:20 AM",
              sunset: "04:40 PM",
              moonrise: "06:15 PM",
              moonset: "07:05 AM",
              moon_phase: "Waning Gibbous",
              moon_illumination: 85,
              is_moon_up: 1,
              is_sun_up: 1
            },
            hour: [
              {
                time_epoch: 1704060000,
                time: "2025-01-04 00:00",
                temp_c: 3.0,
                temp_f: 37.4,
                is_day: 0,
                condition: {
                  text: "Clear",
                  icon: "//cdn.weatherapi.com/weather/64x64/night/113.png",
                  code: 1000
                },
                wind_mph: 5.0,
                wind_kph: 8.0,
                wind_degree: 250,
                wind_dir: "W",
                pressure_mb: 1015,
                pressure_in: 29.97,
                precip_mm: 0.0,
                precip_in: 0.0,
                snow_cm: 0.0,
                humidity: 70,
                cloud: 10,
                feelslike_c: 1.0,
                feelslike_f: 33.8,
                windchill_c: 1.0,
                windchill_f: 33.8,
                heatindex_c: 3.0,
                heatindex_f: 37.4,
                dewpoint_c: -1.0,
                dewpoint_f: 30.2,
                will_it_rain: 0,
                chance_of_rain: 0,
                will_it_snow: 0,
                chance_of_snow: 0,
                vis_km: 10.0,
                vis_miles: 6.2,
                gust_mph: 7.0,
                gust_kph: 11.3,
                uv: 0
              }
            ]
          }
        ]
      }
    };
  
    // Directly use forecastData
    console.log("data >> forecastData :: ", forecastData);
    return forecastData;
  }
  
}

